import type { PokemonType, NatureData, NatureName, StatKey } from "./types";

export const TYPE_COLORS: Record<PokemonType, string> = {
  normal: "#A8A878",
  fire: "#F08030",
  water: "#6890F0",
  electric: "#F8D030",
  grass: "#78C850",
  ice: "#98D8D8",
  fighting: "#C03028",
  poison: "#A040A0",
  ground: "#E0C068",
  flying: "#A890F0",
  psychic: "#F85888",
  bug: "#A8B820",
  rock: "#B8A038",
  ghost: "#705898",
  dragon: "#7038F8",
  dark: "#705848",
  steel: "#B8B8D0",
  fairy: "#EE99AC",
};

export const TYPE_ABBREVIATIONS: Record<PokemonType, string> = {
  normal: "NRM",
  fire: "FIR",
  water: "WTR",
  electric: "ELC",
  grass: "GRS",
  ice: "ICE",
  fighting: "FGT",
  poison: "PSN",
  ground: "GRD",
  flying: "FLY",
  psychic: "PSY",
  bug: "BUG",
  rock: "RCK",
  ghost: "GHO",
  dragon: "DRG",
  dark: "DRK",
  steel: "STL",
  fairy: "FAI",
};

export const ALL_TYPES: PokemonType[] = [
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy",
];

export const DIFFICULTY_LABELS: Record<string, string> = {
  vanilla: "Vanilla",
  difficult: "Difficult",
  expert: "Expert",
  insane: "Insane",
};

export const NATURES: NatureData[] = [
  { name: "Hardy", increased: null, decreased: null },
  { name: "Lonely", increased: "attack", decreased: "defense" },
  { name: "Brave", increased: "attack", decreased: "speed" },
  { name: "Adamant", increased: "attack", decreased: "spAttack" },
  { name: "Naughty", increased: "attack", decreased: "spDefense" },
  { name: "Bold", increased: "defense", decreased: "attack" },
  { name: "Docile", increased: null, decreased: null },
  { name: "Relaxed", increased: "defense", decreased: "speed" },
  { name: "Impish", increased: "defense", decreased: "spAttack" },
  { name: "Lax", increased: "defense", decreased: "spDefense" },
  { name: "Timid", increased: "speed", decreased: "attack" },
  { name: "Hasty", increased: "speed", decreased: "defense" },
  { name: "Serious", increased: null, decreased: null },
  { name: "Jolly", increased: "speed", decreased: "spAttack" },
  { name: "Naive", increased: "speed", decreased: "spDefense" },
  { name: "Modest", increased: "spAttack", decreased: "attack" },
  { name: "Mild", increased: "spAttack", decreased: "defense" },
  { name: "Quiet", increased: "spAttack", decreased: "speed" },
  { name: "Bashful", increased: null, decreased: null },
  { name: "Rash", increased: "spAttack", decreased: "spDefense" },
  { name: "Calm", increased: "spDefense", decreased: "attack" },
  { name: "Gentle", increased: "spDefense", decreased: "defense" },
  { name: "Sassy", increased: "spDefense", decreased: "speed" },
  { name: "Careful", increased: "spDefense", decreased: "spAttack" },
  { name: "Quirky", increased: null, decreased: null },
];

export const STAT_LABELS: Record<StatKey, string> = {
  attack: "Atk",
  defense: "Def",
  spAttack: "SpA",
  spDefense: "SpD",
  speed: "Spe",
};
