import type {
  Pokemon,
  Location,
  Trainer,
  Item,
  Mission,
  ProgressionData,
  GameData,
} from "./types";

// Data is imported statically at build time for the static export.
// Each JSON file is generated by the scrapers in scripts/scrapers/.

let cachedData: GameData | null = null;

async function loadJson<T>(path: string): Promise<T> {
  const mod = await import(`../../data/${path}`);
  return mod.default as T;
}

export async function loadGameData(): Promise<GameData> {
  if (cachedData) return cachedData;

  const [pokemon, locations, trainers, items, missions, progression] =
    await Promise.all([
      loadJson<Pokemon[]>("pokemon.json"),
      loadJson<Location[]>("locations.json"),
      loadJson<Trainer[]>("trainers.json"),
      loadJson<Item[]>("items.json"),
      loadJson<Mission[]>("missions.json"),
      loadJson<ProgressionData>("progression.json"),
    ]);

  cachedData = { pokemon, locations, trainers, items, missions, progression };
  return cachedData;
}

export function getPokemonById(
  pokemon: Pokemon[],
  id: string
): Pokemon | undefined {
  return pokemon.find((p) => p.id === id);
}

export function getLocationById(
  locations: Location[],
  id: string
): Location | undefined {
  return locations.find((l) => l.id === id);
}

export function getTrainerById(
  trainers: Trainer[],
  id: string
): Trainer | undefined {
  return trainers.find((t) => t.id === id);
}

export function searchPokemon(
  pokemon: Pokemon[],
  query: string
): Pokemon[] {
  const q = query.toLowerCase().trim();
  if (!q) return pokemon;
  return pokemon.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.types.some((t) => t.includes(q)) ||
      p.dexNumber.toString() === q
  );
}
