/**
 * Extract species, moves, and items lookup tables from the
 * Pokemon Unbound Cheat Engine table (.CT) file.
 *
 * Usage: tsx scripts/extract-ct-tables.ts [path-to-ct-file]
 *
 * Generates:
 *   src/lib/save-data/species.ts
 *   src/lib/save-data/moves.ts
 *   src/lib/save-data/items.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const ctPath =
  process.argv[2] ??
  resolve(
    process.env.HOME!,
    "Downloads/Pokemon_Unbound_2.0.3.2_V2.1.CT"
  );

const ct = readFileSync(ctPath, "utf-8");

function extractDropdown(marker: string): Map<number, string> {
  const idx = ct.indexOf(marker);
  if (idx === -1) throw new Error(`Marker not found: ${marker}`);

  // Find the surrounding quotes of the Lua string
  const lineStart = ct.lastIndexOf('"', idx);
  const lineEnd = ct.indexOf('"', idx + marker.length);
  const raw = ct.slice(lineStart + 1, lineEnd);

  const map = new Map<number, string>();
  for (const entry of raw.split("\\n")) {
    const colon = entry.indexOf(":");
    if (colon === -1) continue;
    const id = parseInt(entry.slice(0, colon), 10);
    const name = entry.slice(colon + 1);
    if (!isNaN(id)) map.set(id, name);
  }
  return map;
}

function mapToTs(
  map: Map<number, string>,
  exportName: string,
  description: string
): string {
  const entries = Array.from(map.entries())
    .sort((a, b) => a[0] - b[0])
    .map(([id, name]) => `  [${id}, ${JSON.stringify(name)}],`)
    .join("\n");

  return `// Auto-generated by scripts/extract-ct-tables.ts -- do not edit manually
// ${description}

export const ${exportName}: ReadonlyMap<number, string> = new Map([
${entries}
]);
`;
}

// --- Species ---
const species = extractDropdown("0:NONE\\n1:BULBASAUR");
console.log(`Species: ${species.size} entries`);

// --- Moves ---
const moves = extractDropdown("1:Pound\\n2:Karate Chop");
console.log(`Moves: ${moves.size} entries`);

// --- Items ---
const items = extractDropdown("1:Master Ball\\n2:Ultra Ball");
console.log(`Items: ${items.size} entries`);

// --- Write files ---
const outDir = resolve(__dirname, "../src/lib/save-data");

writeFileSync(
  resolve(outDir, "species.ts"),
  mapToTs(species, "SPECIES", `Species ID -> name (${species.size} entries)`)
);

writeFileSync(
  resolve(outDir, "moves.ts"),
  mapToTs(moves, "MOVES", `Move ID -> name (${moves.size} entries)`)
);

writeFileSync(
  resolve(outDir, "items.ts"),
  mapToTs(items, "ITEMS", `Item ID -> name (${items.size} entries)`)
);

console.log("Done! Files written to src/lib/save-data/");
